"""Generate browser tokens from the existing Godot design-system source."""
from pathlib import Path
import json,re,sys
root=Path(__file__).resolve().parents[1]
values={}
for name,expr in re.findall(r'^const (\w+) := ([^\n]+)',(root/'ui/design_tokens.gd').read_text(),re.M):
 expr=expr.strip()
 color=re.fullmatch(r'Color\("([0-9a-fA-F]+)"\)',expr)
 if color: values[name]='#'+color[1]
 elif re.fullmatch(r'\d+(\.\d+)?',expr): values[name]=float(expr) if '.' in expr else int(expr)
 elif expr in values: values[name]=values[expr]
 elif match:=re.fullmatch(r'(\w+) - (\w+)',expr):
  if all(key in values for key in match.groups()): values[name]=values[match[1]]-values[match[2]]
css='/* Generated by web/generate_tokens.py; edit ui/design_tokens.gd. */\n:root{\n'
for key,value in values.items():
 if key.startswith(('SPACE_','RADIUS_','TYPE_','WEB_CONTROL_','WEB_DESKTOP_','WEB_PANEL_','WEB_CARD_','WEB_HUD_','WEB_WIN_COIN_SIZE')) or key in ['BODY_TYPE_PX','TAP_MIN']:
  css+=f'--{key.lower().replace("_","-")}:{value}px;\n'
 elif isinstance(value,str) and value.startswith('#'): css+=f'--{key.lower().replace("_","-")}:{value};\n'
for token in ['BUTTON','ACTION_GO','ACTION_CASH']:
 raw=values[token].lstrip('#')
 channels=[int(raw[i:i+2],16)/255 for i in [0,2,4]]
 for suffix,amount in [('top',0.08 if token=='BUTTON' else 0.20),('bottom',-0.09 if token=='BUTTON' else -0.14),('edge',0.45),('shadow',-0.55)]:
  result=[c+(1-c)*amount if amount>=0 else c*(1+amount) for c in channels]
  color='#'+''.join(f'{round(c*255):02x}' for c in result)
  css+=f'--{token.lower().replace("_","-")}-{suffix}:{color};\n'
css+='}\n' 
source=(root/'web/ui.source.css').read_text()
for key in ['CRASH_MEDIUM_BREAKPOINT','CRASH_LAPTOP_BREAKPOINT','CRASH_DESKTOP_BREAKPOINT','MODAL_PHONE_BREAKPOINT']:
 source=source.replace('__'+key+'__',str(values[key]))
source=source.replace('__PHONE_MAX__',str(values['MODAL_PHONE_BREAKPOINT']-1))
outputs={'tokens.css':css,'ui.css':source,'tokens.js':'window.CrashTokens='+json.dumps(values)+';\n'}
for name,content in outputs.items():
 p=root/'web'/name
 if '--check' in sys.argv:
  if not p.exists() or p.read_text()!=content: raise SystemExit(f'Regenerate {name}')
 else: p.write_text(content)
print('WEB TOKENS: PASS')
